name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout
        run: npm install
      - name: Package
        run: npm run make:win --if-present
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "out/make/squirrel.windows/x64/WahtsonElectron-Installer.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
